// <auto-generated />
using System;
using JoseEnLaura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoseEnLaura.Migrations
{
    [DbContext(typeof(WeddingDbContext))]
    [Migration("20260612172347_AddWeddingLocations")]
    partial class AddWeddingLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JoseEnLaura.Data.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lianne",
                            Role = "CeremonyMaster"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chris",
                            Role = "CeremonyMaster"
                        },
                        new
                        {
                            Id = 3,
                            Name = "José",
                            Role = "Standard"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Laura",
                            Role = "Standard"
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AttendingCeremony")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendingDinner")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendingEvening")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CheckedInCeremonyAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedInDinnerAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedInPartyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietaryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "huwelijkjoseenlaura@hotmail.com",
                            Name = "Lianne",
                            Phone = "0612345678",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "huwelijkjoseenlaura@hotmail.com",
                            Name = "Chris",
                            Phone = "0612345678",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.DressCodeColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameNl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DressCodeColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hex = "#FBF1EE",
                            NameEn = "Cream",
                            NameNl = "Crème",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Hex = "#EFD3D0",
                            NameEn = "Blush",
                            NameNl = "Blush",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Hex = "#DDB3B8",
                            NameEn = "Rosé",
                            NameNl = "Rosé",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Hex = "#C98B96",
                            NameEn = "Dusty Rose",
                            NameNl = "Oudroze",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Hex = "#A85D6E",
                            NameEn = "Mauve",
                            NameNl = "Mauve",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Hex = "#7A4F54",
                            NameEn = "Plum",
                            NameNl = "Pruim",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("AnswerEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FaqItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Alleen als ze expliciet zijn uitgenodigd.",
                            Question = "Zijn kinderen welkom?",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "In overleg.",
                            Question = "Mag ik een +1 meenemen?",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Answer = "16 april.",
                            Question = "Tot wanneer kan ik mijn aanwezigheid doorgeven?",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Meld je af door te mailen naar het e-mail adres: huwelijkremyenmarit@hotmail.com.",
                            Question = "Wat moet ik doen als ik ziek ben?",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Met het OV is het vanaf de dichtstbijzijnde bushalte 3 minuten lopen (280m).\nMet de auto zijn er genoeg parkeerplaatsen!\nJe altijd zelf een taxi huren.\nKen je iemand die mee gaat? Misschien kan je meerijden!",
                            Question = "Wat voor vervoer is er mogelijk naar de locatie?",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Answer = "U kan contact opnemen met bijvoorbeeld één van deze bedrijven:\ninsert taxi company nearby...",
                            Question = "Wilt u met de taxi komen?",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.GeneralNoteComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("GeneralNoteEntryId")
                        .HasColumnType("int");

                    b.Property<string>("MentionedUserIds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GeneralNoteEntryId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("GeneralNoteComments");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.GeneralNoteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("MentionedUserIds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("CreatedById");

                    b.ToTable("GeneralNoteEntries");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InvitedFor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PhotoSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhotoSessions");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PhotoSessionGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("PhotoSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("PhotoSessionId", "GuestId")
                        .IsUnique();

                    b.ToTable("PhotoSessionGuests");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedById");

                    b.ToTable("PlanningAttachments");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("NoteId", "Timestamp");

                    b.ToTable("PlanningAuditLogs");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndentLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCollapsed")
                        .HasColumnType("bit");

                    b.Property<string>("ItemStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("NoteId");

                    b.ToTable("PlanningBlocks");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlanningCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#f4a261",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🌅",
                            Name = "Ochtend",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#e76f51",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "💒",
                            Name = "Ceremonie",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#2a9d8f",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "📸",
                            Name = "Foto's",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#264653",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🍽️",
                            Name = "Diner",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#e9c46a",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "🎉",
                            Name = "Feest",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#606c38",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "📍",
                            Name = "Locatie",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = "#bc6c25",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "📋",
                            Name = "Algemeen",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<string>("MentionedUserIds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("BlockId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("PlanningComments");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPinnedInfo")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Deadline");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PlanningNotes");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningNoteVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("NoteId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PlanningNoteVersions");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Play", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("NeedsBeamer")
                        .HasColumnType("bit");

                    b.Property<string>("Requirements")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId")
                        .IsUnique();

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ScheduleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Welkom met een drankje",
                            SortOrder = 1,
                            Time = "13:30",
                            Title = "Ontvangst"
                        },
                        new
                        {
                            Id = 2,
                            Description = "De trouwceremonie",
                            SortOrder = 2,
                            Time = "14:00",
                            Title = "Ceremonie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Proosten op het bruidspaar",
                            SortOrder = 3,
                            Time = "15:00",
                            Title = "Toost & Felicitaties"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Foto's met familie en vrienden",
                            SortOrder = 4,
                            Time = "16:00",
                            Title = "Groepsfoto's"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Samen genieten van een heerlijk diner",
                            SortOrder = 5,
                            Time = "17:30",
                            Title = "Diner"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dansen en feesten!",
                            SortOrder = 6,
                            Time = "19:00",
                            Title = "Avondfeest"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Het aansnijden van de taart (lekker op tijd om 20.30 lol)",
                            SortOrder = 7,
                            Time = "20:30",
                            Title = "Bruidstaart"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bedankt voor deze mooie dag!",
                            SortOrder = 8,
                            Time = "00:00",
                            Title = "Afsluiting"
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.SiteImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slot")
                        .IsUnique();

                    b.ToTable("SiteImages");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.SiteText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ValueEn")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SiteTexts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "hero.pre",
                            Label = "Hero — bovenste tekst",
                            Value = "Wij gaan trouwen!"
                        },
                        new
                        {
                            Id = 2,
                            Key = "hero.title",
                            Label = "Hero — titel",
                            Value = "José & Laura"
                        },
                        new
                        {
                            Id = 3,
                            Key = "hero.date",
                            Label = "Hero — datum",
                            Value = "17 oktober 2026"
                        },
                        new
                        {
                            Id = 4,
                            Key = "rsvp.title",
                            Label = "RSVP — titel",
                            Value = "Aanwezigheid indienen"
                        },
                        new
                        {
                            Id = 5,
                            Key = "rsvp.subtitle",
                            Label = "RSVP — ondertitel",
                            Value = "Laat ons weten of je erbij bent — graag vóór 17 september 2026"
                        },
                        new
                        {
                            Id = 6,
                            Key = "rsvp.success.attending",
                            Label = "RSVP — bevestiging (aanwezig)",
                            Value = "Wat fijn dat je erbij bent! We kijken ernaar uit."
                        },
                        new
                        {
                            Id = 7,
                            Key = "rsvp.success.notattending",
                            Label = "RSVP — bevestiging (niet aanwezig)",
                            Value = "We hebben je antwoord opgeslagen. Hopelijk zien we je snel!"
                        },
                        new
                        {
                            Id = 8,
                            Key = "help.title",
                            Label = "Hulp nodig — titel",
                            Value = "Hulp nodig?"
                        },
                        new
                        {
                            Id = 9,
                            Key = "help.subtitle",
                            Label = "Hulp nodig — ondertitel",
                            Value = "Kom je er niet uit? Kies dan één van onderstaande contactopties:"
                        },
                        new
                        {
                            Id = 10,
                            Key = "story.title",
                            Label = "Welkom — titel",
                            Value = "Welkom!"
                        },
                        new
                        {
                            Id = 11,
                            Key = "story.text",
                            Label = "Welkom — tekst",
                            Value = "Met heel veel plezier nodigen wij jullie uit voor onze bruiloft. Het wordt een onvergetelijke dag en we hopen dat jullie erbij zijn om dit samen met ons te vieren!"
                        },
                        new
                        {
                            Id = 12,
                            Key = "fullphoto.quote",
                            Label = "Foto — quote",
                            Value = "\"De beste dingen in het leven zijn de mensen van wie je houdt, de plekken waar je bent geweest en de herinneringen die je hebt gemaakt.\""
                        },
                        new
                        {
                            Id = 13,
                            Key = "planning.title",
                            Label = "Programma — titel",
                            Value = "Programma"
                        },
                        new
                        {
                            Id = 14,
                            Key = "planning.subtitle",
                            Label = "Programma — ondertitel",
                            Value = "Een overzicht van de dag"
                        },
                        new
                        {
                            Id = 15,
                            Key = "location.title",
                            Label = "Locatie — titel",
                            Value = "Locatie"
                        },
                        new
                        {
                            Id = 16,
                            Key = "footer.names",
                            Label = "Footer — namen",
                            Value = "José & Laura"
                        },
                        new
                        {
                            Id = 17,
                            Key = "footer.date",
                            Label = "Footer — datum",
                            Value = "17 · 10 · 2026"
                        },
                        new
                        {
                            Id = 18,
                            Key = "faq.title",
                            Label = "FAQ — titel",
                            Value = "Veelgestelde vragen"
                        },
                        new
                        {
                            Id = 19,
                            Key = "wedding.date",
                            Label = "Trouwdatum (voor aftelteller)",
                            Value = "2026-10-17"
                        },
                        new
                        {
                            Id = 20,
                            Key = "dresscode.title",
                            Label = "Dresscode — titel",
                            Value = "Dresscode"
                        },
                        new
                        {
                            Id = 21,
                            Key = "dresscode.subtitle",
                            Label = "Dresscode — ondertitel",
                            Value = "Wij vragen onze gasten om zich te kleden in de volgende kleurtinten",
                            ValueEn = "We kindly ask our guests to dress in the following colour tones"
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.UserBlockVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastVisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("UserId", "BlockId")
                        .IsUnique();

                    b.ToTable("UserBlockVisits");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.UserNoteVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastVisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("UserId", "NoteId")
                        .IsUnique();

                    b.ToTable("UserNoteVisits");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("VisitedAt");

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.WeddingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("WeddingLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Almeloseweg 113, 7615 NA",
                            AddressLine2 = "Harbrinkhoek",
                            Icon = "&#9962;",
                            Phone = "0546 629 962",
                            SortOrder = 1,
                            Title = "Ceremonie",
                            TitleEn = "Ceremony",
                            VenueName = "Kampkuiper"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "Almeloseweg 113, 7615 NA",
                            AddressLine2 = "Harbrinkhoek",
                            Icon = "&#127860;",
                            Phone = "0546 629 962",
                            SortOrder = 2,
                            Title = "Diner",
                            TitleEn = "Dinner",
                            VenueName = "Kampkuiper"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "Almeloseweg 113, 7615 NA",
                            AddressLine2 = "Harbrinkhoek",
                            Icon = "&#127878;",
                            Phone = "0546 629 962",
                            SortOrder = 3,
                            Title = "Feest",
                            TitleEn = "Party",
                            VenueName = "Kampkuiper"
                        });
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Attendance", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.Guest", "Guest")
                        .WithOne("Attendance")
                        .HasForeignKey("JoseEnLaura.Data.Models.Attendance", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.GeneralNoteComment", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.PlanningAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.GeneralNoteEntry", "GeneralNoteEntry")
                        .WithMany("Comments")
                        .HasForeignKey("GeneralNoteEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.GeneralNoteComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Attachment");

                    b.Navigation("CreatedBy");

                    b.Navigation("GeneralNoteEntry");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.GeneralNoteEntry", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.PlanningAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PhotoSessionGuest", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.Guest", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.PhotoSession", "PhotoSession")
                        .WithMany("Guests")
                        .HasForeignKey("PhotoSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("PhotoSession");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningAttachment", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningAuditLog", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.PlanningNote", "Note")
                        .WithMany("AuditLogs")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningBlock", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JoseEnLaura.Data.Models.PlanningAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JoseEnLaura.Data.Models.PlanningNote", "Note")
                        .WithMany("Blocks")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Attachment");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningComment", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.PlanningAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JoseEnLaura.Data.Models.PlanningBlock", "Block")
                        .WithMany("Comments")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.PlanningComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Attachment");

                    b.Navigation("Block");

                    b.Navigation("CreatedBy");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningNote", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JoseEnLaura.Data.Models.PlanningCategory", "Category")
                        .WithMany("Notes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningNoteVersion", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.PlanningNote", "Note")
                        .WithMany("Versions")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Play", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.Attendance", "Attendance")
                        .WithOne("Play")
                        .HasForeignKey("JoseEnLaura.Data.Models.Play", "AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.ScheduleItem", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.ScheduleItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.UserBlockVisit", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.PlanningBlock", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.UserNoteVisit", b =>
                {
                    b.HasOne("JoseEnLaura.Data.Models.PlanningNote", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoseEnLaura.Data.Models.AdminUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Attendance", b =>
                {
                    b.Navigation("Play");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.GeneralNoteComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.GeneralNoteEntry", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.Guest", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PhotoSession", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningBlock", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningCategory", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.PlanningNote", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Blocks");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("JoseEnLaura.Data.Models.ScheduleItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
